name: DDD CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Copy Environment File
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Fix issues with CodeSniffer
        run: ./vendor/bin/phpcbf --standard=PSR12 -s app

      - name: Check for errors with CodeSniffer
        run: ./vendor/bin/phpcs --standard=PSR12 -s app

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse app --memory-limit=-1

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

#runs-on: ubuntu-latest
#  steps:
#      - uses: actions/checkout@master
#        - name: Deploy to staging
#          env:
#            VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
#            GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
#          uses: teamnovu/vapor-action@master
#          with:
#            args: deploy staging



