name: DDD CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-progress --no-scripts --no-suggest --prefer-dist

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run CodeSniffer
        run: vendor/bin/phpcs

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze

      - name: Run Unit Tests
        run: vendor/bin/phpunit
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Deploy to Server
#        uses: easingthemes/ssh-deploy@v2
#        with:
#          server: ${{ secrets.DEPLOY_SERVER }}
#          remote_user: ${{ secrets.DEPLOY_USER }}
#          remote_path: ${{ secrets.DEPLOY_PATH }}
#          key: ${{ secrets.DEPLOY_KEY }}
#          source: '.'
